theme: jekyll-theme-modernist
github:
  zip_url: http://example.com/download.zip
  project_tagline: <a href="https://dashboard.unzoner.com/sub"><img src="https://api-dev.belodedenko.me/api/v1.0/countries/available/flags.png" alt="Available countries"></a>
  
